apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: my-scheduler
leaderElection:
  leaderElect: false
  resourceLock: endpoints
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-scheduler-config
    namespace: kube-system
  data:
    scheduler-config.yaml: |
      apiVersion: kubescheduler.config.k8s.io/v1
      kind: KubeSchedulerConfiguration
      profiles:
        - schedulerName: my-scheduler
      leaderElection:
        leaderElect: false
        resourceLock: endpoints
        resourceName: my-scheduler