apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replicaset
  labels:
    app: my-replicaset
spec:
  template:
    metadata:
      labels:
        app: my-replicaset
    spec:
      containers:
      - name: my-replicaset
        image: nginx:1.7.9
        ports:
        - containerPort: 80
  replicas: 3