apiVersion: v1
kind: Service
metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend
    type: front-end
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: httpd-frontend
    type: front-end