apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    tier: node-role.kubernetes.io/control-plane
spec:
  containers:
  - name: static-busybox
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']